# Generated by Django 4.1 on 2022-08-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="students",
            field=models.IntegerField(default=0),
        ),
    ]
