# Generated by Django 4.1 on 2022-08-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_content_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="is_active",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="content",
            name="students",
            field=models.IntegerField(),
        ),
    ]
